"use client";

import { useEffect,useState } from "react";
type Row=Record<string,any>;
const eventTypes=["new_ride_available","driver_offer","ride_matched","reminder_24h","reminder_1h","driver_arriving","last_minute_cancellation","pickup_changed","platform_test"];
function money(cents:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(cents||0)/100);}

export default function NotificationRoutingAdmin(){
 const[notificationType,setNotificationType]=useState("ride_matched"),[title,setTitle]=useState("BandWagon ride update"),[body,setBody]=useState("Your BandWagon ride has been matched."),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[policies,setPolicies]=useState<any[]>([]),[result,setResult]=useState<any>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[organizations,setOrganizations]=useState<Row[]>([]),[org,setOrg]=useState(""),[health,setHealth]=useState<Row|null>(null);
 const adminHeaders={"content-type":"application/json"};
 async function loadHealth(id=org){const qs=id?`?organizationId=${encodeURIComponent(id)}`:"",r=await fetch(`/api/admin/operations${qs}`),d=await r.json().catch(()=>({}));if(r.status===401){location.href="/login";return;}if(!r.ok){setMessage(d.error||"Unable to load notification health");return;}setOrganizations(d.organizations||[]);if(!id&&d.organizations?.[0]){setOrg(d.organizations[0].id);void loadHealth(d.organizations[0].id);return;}setHealth(d.dashboard?.notifications||null);}
 useEffect(()=>{void loadHealth("");},[]);
 async function loadPolicies(){setMessage("");const r=await fetch("/api/admin/notification-routing"),d=await r.json().catch(()=>({}));if(!r.ok)return setMessage(d.error||"Unable to load notification policies");setPolicies(d.policies||[]);}
 async function testRouting(){setBusy(true);setResult(null);setMessage("Routing notification...");try{const r=await fetch("/api/admin/notification-routing",{method:"POST",headers:adminHeaders,body:JSON.stringify({notificationType,title,body,phone:phone||null,email:email||null})}),d=await r.json().catch(()=>({}));if(!r.ok)return setMessage(d.error||"Notification routing failed");setResult(d);setMessage("Notification routing completed.");}finally{setBusy(false);}}
 const card={marginTop:20,padding:20,border:"1px solid #dbe3ef",borderRadius:16,background:"white"} as const,input={display:"block",width:"100%",padding:12,margin:"8px 0 14px",border:"1px solid #cbd5e1",borderRadius:8,boxSizing:"border-box" as const};
 return <main style={{maxWidth:1050,margin:"40px auto",padding:"0 20px",fontFamily:"system-ui,sans-serif"}}>
  <section style={{background:"#101b33",color:"white",padding:28,borderRadius:22}}><div style={{fontSize:13,fontWeight:800,letterSpacing:1}}>BANDWAGON ADMIN</div><h1 style={{fontSize:38,margin:"6px 0"}}>Notification Delivery Health</h1><p style={{margin:0,opacity:.9}}>Push first. Email when useful. SMS / RCS only when urgency or fallback policy calls for it.</p></section>
  <section style={card}><label><strong>Organization</strong></label><select value={org} onChange={e=>{setOrg(e.target.value);void loadHealth(e.target.value);}} style={input}>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></section>
  {health&&<><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><div style={card}><b>Delivery Success</b><div style={{fontSize:32,fontWeight:950}}>{health.successRate}%</div></div><div style={card}><b>Failures</b><div style={{fontSize:32,fontWeight:950}}>{health.failed}</div></div><div style={card}><b>SMS / RCS</b><div style={{fontSize:32,fontWeight:950}}>{health.smsCount}</div></div><div style={card}><b>Messaging Cost</b><div style={{fontSize:32,fontWeight:950}}>{money(health.totalCostCents)}</div></div></section><section style={card}><h2>Channel Health</h2><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">Channel</th><th>Status</th><th>Count</th><th style={{textAlign:"right"}}>Estimated Cost</th></tr></thead><tbody>{health.rows.map((r:Row,i:number)=><tr key={i}><td style={{padding:"8px 0"}}>{String(r.channel).toUpperCase()}</td><td align="center">{r.status}</td><td align="center">{r.count}</td><td style={{textAlign:"right"}}>{money(r.estimatedCostCents)}</td></tr>)}</tbody></table><p style={{fontSize:13,color:"#64748b",marginBottom:0}}>Routine BandWagon traffic remains Push-first to reduce cost. Safety-critical delivery can still use immediate SMS / RCS.</p></section><section style={card}><h2>Recent Failures</h2>{!health.recentFailures.length?<p>No recent failed or undelivered notifications.</p>:<ul>{health.recentFailures.map((r:Row,i:number)=><li key={i}>{String(r.channel).toUpperCase()} · {String(r.notification_type).replaceAll("_"," ")} · {new Date(r.created_at).toLocaleString()}</li>)}</ul>}</section></>}
  <section style={card}><h2>Routing Policy Test</h2><p style={{color:"#64748b"}}>Platform-admin testing uses your signed-in session and stays separate from organization delivery-health reporting.</p><button onClick={loadPolicies}>Load Routing Policies</button></section>
  {policies.length>0&&<section style={card}><h2>Current Policies</h2><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">Event</th><th>Urgency</th><th>Push</th><th>Email fallback</th><th>SMS fallback</th><th>SMS immediate</th></tr></thead><tbody>{policies.map(p=><tr key={p.type}><td>{p.type}</td><td align="center">{p.urgency}</td><td align="center">{p.push?"Yes":"No"}</td><td align="center">{p.emailFallback?"Yes":"No"}</td><td align="center">{p.smsFallback?"Yes":"No"}</td><td align="center">{p.smsImmediate?"Yes":"No"}</td></tr>)}</tbody></table></section>}
  <section style={card}><h2>Route A Test Notification</h2><label>Event type</label><select value={notificationType} onChange={e=>setNotificationType(e.target.value)} style={input}>{eventTypes.map(type=><option key={type} value={type}>{type}</option>)}</select><label>Title</label><input value={title} onChange={e=>setTitle(e.target.value)} style={input}/><label>Message</label><textarea value={body} onChange={e=>setBody(e.target.value)} rows={4} style={input}/><label>Test phone (optional, E.164)</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+14695551212" style={input}/><label>Test email (optional)</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" style={input}/><button disabled={busy} onClick={testRouting}>{busy?"Routing...":"Run Routing Test"}</button></section>
  {message&&<p style={{padding:14,background:"#f8fafc",borderRadius:10}}>{message}</p>}{result&&<section style={card}><h2>Routing Result</h2><p>Correlation ID: <code>{result.correlationId}</code></p><p>Urgency: <strong>{result.urgency}</strong></p><p>Push: <strong>{result.push?.accepted||0}</strong> accepted / {result.push?.attempted||0} attempted</p><p>SMS / RCS: <strong>{result.messaging?.accepted?"Accepted":result.messaging?.skipped||"Not sent"}</strong></p><p>Email: <strong>{result.email?.accepted?"Accepted":result.email?.reason||"Not sent"}</strong></p></section>}
 </main>;
}
