"use client";

import { useEffect,useState } from "react";

type Row=Record<string,any>;
function money(cents:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(cents||0)/100);}

export default function OperationsAdmin(){
  const [organizations,setOrganizations]=useState<Row[]>([]);const [org,setOrg]=useState("");const [d,setD]=useState<Row|null>(null);const [message,setMessage]=useState("");const [working,setWorking]=useState(false);
  async function load(organizationId=org){const qs=organizationId?`?organizationId=${encodeURIComponent(organizationId)}`:"";const r=await fetch(`/api/admin/operations${qs}`);const x=await r.json().catch(()=>({}));if(r.status===401){location.href="/login";return;}if(!r.ok){setMessage(x.error||"Unable to load operations dashboard");return;}setOrganizations(x.organizations||[]);if(!organizationId&&x.organizations?.[0]){setOrg(x.organizations[0].id);void load(x.organizations[0].id);return;}setD(x.dashboard||null);}
  useEffect(()=>{void load("");},[]);
  async function post(body:Row){setWorking(true);setMessage("");const r=await fetch("/api/admin/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json().catch(()=>({}));setWorking(false);if(!r.ok){setMessage(x.error||"Admin action failed");return;}setD(x.dashboard);setMessage("Updated.");}
  const card={background:"white",border:"1px solid #e2e8f0",borderRadius:16,padding:18} as const;
  const button={padding:"8px 11px",border:"1px solid #cbd5e1",borderRadius:8,background:"white",cursor:"pointer",fontWeight:800} as const;
  const metric=(label:string,value:any,detail?:string)=><div style={card}><div style={{fontSize:12,fontWeight:900,letterSpacing:.7,color:"#64748b"}}>{label.toUpperCase()}</div><div style={{fontSize:32,fontWeight:950,marginTop:5}}>{value}</div>{detail&&<div style={{fontSize:13,color:"#64748b",marginTop:4}}>{detail}</div>}</div>;
  return <main style={{maxWidth:1180,margin:"32px auto",padding:"0 20px",fontFamily:"system-ui,sans-serif",background:"#f8fafc"}}>
    <header style={{background:"#101b33",color:"white",padding:26,borderRadius:22,marginBottom:18}}><div style={{fontSize:13,fontWeight:900,letterSpacing:1}}>BANDWAGON ADMIN</div><h1 style={{fontSize:38,margin:"6px 0"}}>Safety & Trust Operations</h1><p style={{margin:0,opacity:.85}}>Ride coverage, driver eligibility, RouteAssist, credential reviews, safety alerts, AI spend, and community funding.</p></header>
    <section style={{...card,marginBottom:18}}><label><strong>Organization</strong></label><select value={org} onChange={e=>{setOrg(e.target.value);void load(e.target.value);}} style={{display:"block",marginTop:7,padding:10,border:"1px solid #cbd5e1",borderRadius:9,minWidth:280}}><option value="">Select organization</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></section>
    {!d?<section style={card}>Choose an organization to load the dashboard.</section>:<>
      <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginBottom:18}}>{metric("Rides Today",d.rides.today,`${d.rides.month} this month`)}{metric("Eligible Drivers",d.drivers.eligible,`${d.drivers.optedIn} opted in`)}{metric("Pending Reviews",d.drivers.pendingReviews)}{metric("Open Safety Alerts",d.safety.open,`${d.safety.month} this month`)}{metric("AI Spend",money(d.ai.totalCostCents),`${d.ai.rows.reduce((s:number,r:Row)=>s+Number(r.jobs||0),0)} jobs`)}{metric("Routing Spend",money(d.routing.totalCostCents),`${d.routing.totalRequests} provider calls`)}{metric("RouteAssist Offers",d.routing.offers,`${d.routing.recommendations} recommendations`)}</section>
      <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:14,marginBottom:18}}>
        <div style={card}><h2 style={{marginTop:0}}>Community Impact</h2><table style={{width:"100%",borderCollapse:"collapse"}}><tbody><tr><td style={{padding:"7px 0"}}>Ride operations (~$0.25 / ride)</td><td style={{textAlign:"right",fontWeight:800}}>{money(d.economics.rideCostCents)}</td></tr><tr><td style={{padding:"7px 0"}}>Driver validation (~$0.50 / driver)</td><td style={{textAlign:"right",fontWeight:800}}>{money(d.economics.driverValidationCostCents)}</td></tr><tr><td style={{padding:"7px 0"}}>AI / document processing</td><td style={{textAlign:"right",fontWeight:800}}>{money(d.economics.aiCostCents)}</td></tr><tr><td style={{padding:"7px 0"}}>RouteAssist / routing</td><td style={{textAlign:"right",fontWeight:800}}>{money(d.economics.routingCostCents)}</td></tr><tr><td style={{padding:"10px 0",borderTop:"1px solid #e2e8f0"}}><strong>Estimated Operating Cost</strong></td><td style={{textAlign:"right",fontWeight:950,borderTop:"1px solid #e2e8f0"}}>{money(d.economics.estimatedOperatingCostCents)}</td></tr><tr><td style={{padding:"7px 0"}}>Community Support</td><td style={{textAlign:"right",fontWeight:800}}>{money(d.economics.supportCents)}</td></tr><tr><td style={{padding:"7px 0"}}><strong>Coverage</strong></td><td style={{textAlign:"right",fontWeight:950}}>{d.economics.coveragePercent}%</td></tr></tbody></table></div>
        <div style={card}><h2 style={{marginTop:0}}>AI / Automation</h2>{!d.ai.rows.length?<p>No AI jobs charged to this organization this month.</p>:<table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={{textAlign:"left"}}>Purpose</th><th>Model</th><th>Jobs</th><th style={{textAlign:"right"}}>Cost</th></tr></thead><tbody>{d.ai.rows.map((r:Row)=><tr key={`${r.purpose}-${r.model_alias}`}><td style={{padding:"8px 0"}}>{String(r.purpose).replaceAll("_"," ")}</td><td style={{textAlign:"center"}}>{r.model_alias}</td><td style={{textAlign:"center"}}>{r.jobs}</td><td style={{textAlign:"right"}}>{money(r.costCents)}</td></tr>)}</tbody></table>}</div>
        <div style={card}><h2 style={{marginTop:0}}>RouteAssist / Routing</h2><table style={{width:"100%",borderCollapse:"collapse"}}><tbody><tr><td style={{padding:"7px 0"}}>Routing Provider Calls</td><td style={{textAlign:"right",fontWeight:800}}>{d.routing.totalRequests}</td></tr><tr><td style={{padding:"7px 0"}}>Cache Hits</td><td style={{textAlign:"right",fontWeight:800}}>{d.routing.cacheHits}</td></tr><tr><td style={{padding:"7px 0"}}>Fallback Estimates</td><td style={{textAlign:"right",fontWeight:800}}>{d.routing.fallbacks}</td></tr><tr><td style={{padding:"7px 0"}}>Recommendations</td><td style={{textAlign:"right",fontWeight:800}}>{d.routing.recommendations}</td></tr><tr><td style={{padding:"7px 0"}}>Driver Offers From RouteAssist</td><td style={{textAlign:"right",fontWeight:800}}>{d.routing.offers}</td></tr><tr><td style={{padding:"7px 0"}}>Recommendation → Offer Rate</td><td style={{textAlign:"right",fontWeight:800}}>{d.routing.recommendations?Math.round(d.routing.offers/d.routing.recommendations*100):0}%</td></tr><tr><td style={{padding:"10px 0",borderTop:"1px solid #e2e8f0"}}><strong>Estimated Routing Cost</strong></td><td style={{textAlign:"right",fontWeight:950,borderTop:"1px solid #e2e8f0"}}>{money(d.routing.totalCostCents)}</td></tr></tbody></table>{d.routing.totalRequests>0&&d.routing.totalCostCents===0&&<p style={{fontSize:12,color:"#64748b",marginBottom:0}}>Set GOOGLE_ROUTES_ESTIMATED_COST_USD_PER_CALL to include a planning cost for Google Routes calls.</p>}</div>
      </section>
      <section style={{...card,marginBottom:18}}><h2 style={{marginTop:0}}>Pending Driver Reviews</h2>{!d.pendingReviews.length?<p>No driver credentials are waiting for review.</p>:d.pendingReviews.map((r:Row)=><div key={`${r.driver_person_id}-${r.requirement_type}`} style={{padding:"13px 0",borderBottom:"1px solid #e2e8f0",display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><strong>{r.preferred_name||r.display_name}</strong> · {String(r.requirement_type).replaceAll("_"," ")}<div style={{fontSize:13,color:"#64748b",marginTop:3}}>{r.original_filename||"No document attached"}{r.expires_at?` · expires ${new Date(r.expires_at).toLocaleDateString()}`:""}</div></div><div style={{display:"flex",gap:7}}><button disabled={working} onClick={()=>post({action:"review_requirement",organizationId:org,driverPersonId:r.driver_person_id,requirementType:r.requirement_type,approve:true,expiresAt:r.expires_at||null})} style={{...button,borderColor:"#86efac"}}>Approve</button><button disabled={working} onClick={()=>post({action:"review_requirement",organizationId:org,driverPersonId:r.driver_person_id,requirementType:r.requirement_type,approve:false})} style={{...button,borderColor:"#fecaca"}}>Reject</button></div></div>)}</section>
      <section style={card}><h2 style={{marginTop:0}}>Expiring Credentials</h2>{!d.expiringCredentials.length?<p>No approved credentials expire in the next 30 days.</p>:<ul>{d.expiringCredentials.map((r:Row,i:number)=><li key={i}>{r.display_name} · {String(r.requirement_type).replaceAll("_"," ")} · {new Date(r.expires_at).toLocaleDateString()}</li>)}</ul>}</section>
    </>}
    {message&&<div style={{position:"fixed",right:20,bottom:20,maxWidth:520,padding:14,borderRadius:12,background:"#101b33",color:"white"}}>{message}</div>}
  </main>;
}
