"use client";

import { useEffect,useState } from "react";

type Row=Record<string,any>;

export default function EventIntakePage(){
  const [orgs,setOrgs]=useState<Row[]>([]);const [org,setOrg]=useState("");const [text,setText]=useState("");const [drafts,setDrafts]=useState<Row[]>([]);const [current,setCurrent]=useState<Row|null>(null);const [message,setMessage]=useState("");const [working,setWorking]=useState(false);
  useEffect(()=>{void bootstrap();},[]);
  async function bootstrap(){const r=await fetch("/api/product");const x=await r.json().catch(()=>({}));if(r.status===401){location.href="/login";return;}const rows=(x.dashboard?.organizations||[]).filter((o:Row)=>['owner','admin','manager'].includes(o.role));setOrgs(rows);if(rows[0]){setOrg(rows[0].id);void loadDrafts(rows[0].id);}}
  async function loadDrafts(id=org){if(!id)return;const r=await fetch(`/api/admin/event-intake?organizationId=${encodeURIComponent(id)}`);const x=await r.json().catch(()=>({}));if(r.ok)setDrafts(x.drafts||[]);}
  async function analyze(){if(!org||!text.trim())return;setWorking(true);setMessage("BandWagon AI is reading the announcement…");const r=await fetch("/api/admin/event-intake",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"analyze",organizationId:org,text})});const x=await r.json().catch(()=>({}));setWorking(false);if(!r.ok){setMessage(x.error||"Unable to analyze event");return;}setCurrent({id:x.result.id,...x.result.proposal});setMessage("Draft ready. Review every field before publishing.");await loadDrafts();}
  async function publish(){if(!current)return;setWorking(true);const r=await fetch("/api/admin/event-intake",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"publish",draftId:current.id,proposal:current})});const x=await r.json().catch(()=>({}));setWorking(false);if(!r.ok){setMessage(x.error||"Unable to publish event");return;}setMessage(`Published: ${x.result.title}`);setCurrent(null);setText("");await loadDrafts();}
  function field(key:string,label:string,type="text"){return <label style={{display:"block",fontWeight:800,marginBottom:12}}>{label}<input type={type} value={current?.[key]||""} onChange={e=>setCurrent(c=>c?{...c,[key]:e.target.value}:c)} style={{display:"block",width:"100%",boxSizing:"border-box",marginTop:6,padding:10,border:"1px solid #cbd5e1",borderRadius:9}}/></label>}
  const button={padding:"11px 14px",border:0,borderRadius:9,background:"#101b33",color:"white",fontWeight:900,cursor:"pointer"} as const;
  return <main style={{maxWidth:1050,margin:"32px auto",padding:"0 20px",fontFamily:"system-ui,sans-serif"}}><div style={{fontSize:13,fontWeight:950,letterSpacing:1,color:"#64748b"}}>BANDWAGON ADMIN</div><h1>AI Event Intake</h1><p style={{color:"#475569"}}>Paste an email, text, or announcement. AI proposes the event; an organization administrator must review and publish it.</p>
    <section style={{background:"white",border:"1px solid #e2e8f0",borderRadius:18,padding:20,marginBottom:18}}><label style={{fontWeight:800}}>Organization<select value={org} onChange={e=>{setOrg(e.target.value);setCurrent(null);void loadDrafts(e.target.value);}} style={{display:"block",width:"100%",marginTop:6,padding:10,border:"1px solid #cbd5e1",borderRadius:9}}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label style={{display:"block",fontWeight:800,marginTop:16}}>Paste announcement<textarea value={text} onChange={e=>setText(e.target.value)} rows={9} placeholder="Guard rehearsal Tuesday at FMHS from 5:30–8:30. Students need rides there by 5:15…" style={{display:"block",width:"100%",boxSizing:"border-box",marginTop:6,padding:12,border:"1px solid #cbd5e1",borderRadius:9,fontFamily:"inherit"}}/></label><button disabled={working||!org||text.trim().length<10} onClick={analyze} style={{...button,marginTop:12}}>{working?"Working…":"Create AI Draft"}</button></section>
    {current&&<section style={{background:"#f8fafc",border:"2px solid #cbd5e1",borderRadius:18,padding:20,marginBottom:18}}><div style={{fontSize:13,fontWeight:950,color:"#64748b"}}>HUMAN REVIEW REQUIRED</div><h2>Review Proposed Event</h2>{field("title","Title")}{field("locationName","Location Name")}{field("locationAddress","Location Address")}{field("startsAt","Starts At")}{field("endsAt","Ends At")}<label style={{display:"block",fontWeight:800,marginBottom:12}}>Description<textarea value={current.description||""} onChange={e=>setCurrent({...current,description:e.target.value})} rows={4} style={{display:"block",width:"100%",boxSizing:"border-box",marginTop:6,padding:10,border:"1px solid #cbd5e1",borderRadius:9}}/></label>{Array.isArray(current.warnings)&&current.warnings.length>0&&<div style={{padding:12,background:"#fff7ed",borderRadius:10,marginBottom:12}}><strong>AI warnings</strong><ul>{current.warnings.map((w:string)=><li key={w}>{w}</li>)}</ul></div>}<button disabled={working} onClick={publish} style={button}>Review Complete - Publish Event</button><p style={{fontSize:13,color:"#64748b"}}>AI cannot publish by itself. This action records the reviewing administrator.</p></section>}
    <section style={{background:"white",border:"1px solid #e2e8f0",borderRadius:18,padding:20}}><h2 style={{marginTop:0}}>Recent Intake</h2>{!drafts.length?<p>No AI event drafts yet.</p>:drafts.map(d=><div key={d.id} style={{padding:"10px 0",borderBottom:"1px solid #e2e8f0"}}><strong>{d.proposed_event?.title||"Untitled draft"}</strong><div style={{fontSize:13,color:"#64748b"}}>{d.status.replaceAll("_"," ")} · {new Date(d.created_at).toLocaleString()}</div></div>)}</section>
    {message&&<div style={{position:"fixed",right:20,bottom:20,maxWidth:520,padding:14,borderRadius:12,background:"#101b33",color:"white"}}>{message}</div>}
  </main>;
}
