"use client";

import { useEffect,useState } from "react";

type Row=Record<string,any>;
const badge=(s:string)=>({display:'inline-block',padding:'4px 8px',borderRadius:999,fontSize:12,fontWeight:900,background:s==='healthy'?'#dcfce7':s==='failed'?'#fee2e2':'#fef3c7',color:s==='healthy'?'#166534':s==='failed'?'#991b1b':'#92400e'} as const);

export default function PlatformHealthPage(){
  const[d,setD]=useState<Row|null>(null),[message,setMessage]=useState('');
  const card={background:'white',border:'1px solid #e2e8f0',borderRadius:16,padding:18} as const;
  async function load(){const r=await fetch('/api/admin/health',{cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok){setMessage(x.error||'Unable to load platform health');return;}setD(x.health);setMessage('');}
  async function resolveError(id:string){const r=await fetch('/api/admin/health',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'resolve_error',id})}),x=await r.json().catch(()=>({}));if(!r.ok){setMessage(x.error||'Unable to resolve application error');return;}await load();}
  useEffect(()=>{void load();const t=setInterval(()=>void load(),60000);return()=>clearInterval(t);},[]);
  return <main style={{maxWidth:1200,margin:'32px auto',padding:'0 20px',fontFamily:'system-ui,sans-serif',background:'#f8fafc'}}>
    <header style={{background:'#101b33',color:'white',padding:28,borderRadius:22,marginBottom:18}}><div style={{fontSize:13,fontWeight:900,letterSpacing:1}}>PLATFORM ADMIN</div><h1 style={{fontSize:40,margin:'6px 0'}}>Platform Health</h1><p style={{margin:0,opacity:.9}}>One place to see what is healthy, degraded, broken, stale, or misconfigured.</p></header>
    {!d?<section style={card}>{message||'Loading health…'}</section>:<>
      <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,marginBottom:18}}><div style={card}><div style={{fontSize:12,fontWeight:900,color:'#64748b'}}>OVERALL</div><div style={{marginTop:8}}><span style={badge(d.overall)}>{String(d.overall).toUpperCase()}</span></div></div><div style={card}><div style={{fontSize:12,fontWeight:900,color:'#64748b'}}>HEALTHY</div><div style={{fontSize:34,fontWeight:950}}>{d.summary.healthy}</div></div><div style={card}><div style={{fontSize:12,fontWeight:900,color:'#64748b'}}>DEGRADED / UNKNOWN</div><div style={{fontSize:34,fontWeight:950}}>{d.summary.degraded}</div></div><div style={card}><div style={{fontSize:12,fontWeight:900,color:'#64748b'}}>FAILED</div><div style={{fontSize:34,fontWeight:950}}>{d.summary.failed}</div></div></section>
      <section style={{...card,marginBottom:18}}><h2 style={{marginTop:0}}>Integrations & Services</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10}}>{d.integrations.map((x:Row)=><div key={x.key} style={{border:'1px solid #e2e8f0',borderRadius:12,padding:14}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong>{x.label}</strong><span style={badge(x.status)}>{x.status}</span></div><div style={{fontSize:13,color:'#64748b',marginTop:7}}>{x.detail}</div></div>)}</div></section>
      <section style={{...card,marginBottom:18}}><h2 style={{marginTop:0}}>Scheduled Jobs</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr><th style={{textAlign:'left'}}>Job</th><th>Status</th><th style={{textAlign:'left'}}>Last Success</th><th style={{textAlign:'left'}}>Last Failure</th><th style={{textAlign:'right'}}>Failures</th><th style={{textAlign:'right'}}>Duration</th></tr></thead><tbody>{d.crons.map((x:Row)=><tr key={x.key} style={{borderTop:'1px solid #e2e8f0'}}><td style={{padding:'11px 0',fontWeight:800}}>{x.label}</td><td style={{textAlign:'center'}}><span style={badge(x.status)}>{x.status}</span></td><td>{x.lastSuccess?new Date(x.lastSuccess).toLocaleString():'Never'}</td><td>{x.lastFailure?new Date(x.lastFailure).toLocaleString():'—'}</td><td style={{textAlign:'right'}}>{x.consecutiveFailures}</td><td style={{textAlign:'right'}}>{x.lastDurationMs!=null?`${x.lastDurationMs} ms`:'—'}</td></tr>)}</tbody></table></div></section>
      <section style={{...card,marginBottom:18}}><h2 style={{marginTop:0}}>Application Errors</h2><p style={{fontSize:13,color:'#64748b'}}>Unhandled server request errors are fingerprinted, redacted, grouped, and reopened automatically if they recur.</p>{d.applicationErrors?.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:850}}><thead><tr><th style={{textAlign:'left'}}>Error</th><th style={{textAlign:'left'}}>Route</th><th style={{textAlign:'right'}}>Occurrences</th><th style={{textAlign:'left'}}>Last seen</th><th></th></tr></thead><tbody>{d.applicationErrors.map((x:Row)=><tr key={x.id} style={{borderTop:'1px solid #e2e8f0'}}><td style={{padding:'11px 8px 11px 0'}}><strong>{x.error_name}</strong><div style={{fontSize:12,color:'#64748b',maxWidth:420}}>{x.message}</div></td><td><code>{x.request_method||''} {x.route_path||'unknown'}</code></td><td style={{textAlign:'right'}}>{x.occurrence_count}</td><td>{new Date(x.last_seen_at).toLocaleString()}</td><td style={{textAlign:'right'}}><button onClick={()=>void resolveError(String(x.id))} style={{padding:'6px 9px',border:'1px solid #cbd5e1',borderRadius:7,background:'white',cursor:'pointer'}}>Resolve</button></td></tr>)}</tbody></table></div>:<p>No open application errors.</p>}</section>
      <section style={{...card,marginBottom:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'center'}}><div><h2 style={{margin:'0 0 4px'}}>Custom Domain Health</h2><div style={{fontSize:13,color:'#64748b'}}>DoDomain watches DNS drift; Cloudflare remains the TLS and edge authority.</div></div><div style={{fontSize:13,color:'#475569'}}>DoDomain API: <strong>{d.domainProviders?.dodomainConfigured?'configured':'missing'}</strong> · Webhook: <strong>{d.domainProviders?.webhookConfigured?'configured':'missing'}</strong> · Cloudflare: <strong>{d.domainProviders?.cloudflareConfigured?'configured':'missing'}</strong></div></div><div style={{display:'flex',gap:12,margin:'14px 0',flexWrap:'wrap'}}><span>Healthy <strong>{d.domainSummary?.healthy||0}</strong></span><span>Degraded <strong>{d.domainSummary?.degraded||0}</strong></span><span>Failed <strong>{d.domainSummary?.failed||0}</strong></span><span>Pending <strong>{d.domainSummary?.pending||0}</strong></span></div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:900}}><thead><tr><th style={{textAlign:'left'}}>Community</th><th style={{textAlign:'left'}}>Domain</th><th>Status</th><th>DNS</th><th>TLS</th><th>Setup</th><th style={{textAlign:'left'}}>Needs Attention</th></tr></thead><tbody>{(d.customDomains||[]).map((x:Row)=><tr key={x.id} style={{borderTop:'1px solid #e2e8f0'}}><td style={{padding:'11px 0',fontWeight:800}}>{x.organization_name}</td><td>{x.hostname}</td><td style={{textAlign:'center'}}><span style={badge(x.healthStatus)}>{x.healthStatus}</span></td><td style={{textAlign:'center'}}>{x.dns_status||'—'}</td><td style={{textAlign:'center'}}>{x.ssl_status||'—'}</td><td style={{textAlign:'center'}}>{x.setup_provider?`${x.setup_mode} / ${x.setup_provider}`:x.setup_mode||'manual'}</td><td style={{color:x.issues?.length?'#92400e':'#64748b'}}>{x.issues?.length?x.issues.join(' · '):'No issues detected'}</td></tr>)}</tbody></table></div></section>
      <section style={card}><h2 style={{marginTop:0}}>Organization Health</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:820}}><thead><tr><th style={{textAlign:'left'}}>Organization</th><th>Status</th><th style={{textAlign:'right'}}>Admins</th><th style={{textAlign:'right'}}>Drivers</th><th style={{textAlign:'left'}}>Needs Attention</th></tr></thead><tbody>{d.organizations.map((o:Row)=><tr key={o.id} style={{borderTop:'1px solid #e2e8f0'}}><td style={{padding:'12px 0',fontWeight:900}}>{o.name}</td><td style={{textAlign:'center'}}><span style={badge(o.status)}>{o.status}</span></td><td style={{textAlign:'right'}}>{o.admins}</td><td style={{textAlign:'right'}}>{o.drivers}</td><td style={{paddingLeft:18,color:o.issues.length?'#92400e':'#64748b'}}>{o.issues.length?o.issues.join(' · '):'No issues detected'}</td></tr>)}</tbody></table></div></section>
    </>}
    {message&&<p style={{marginTop:14,padding:12,background:'#fff7ed',border:'1px solid #fed7aa',borderRadius:10}}>{message}</p>}
  </main>;
}
