"use client";

import { useEffect,useState } from "react";
import { AppNav,appCardStyle,appPageStyle } from "@/components/app-nav";

type Row=Record<string,any>;

export default function DriverPage(){
  const [d,setD]=useState<Row|null>(null);const [message,setMessage]=useState("");const [working,setWorking]=useState(false);
  const [org,setOrg]=useState("");const [capacity,setCapacity]=useState("4");const [vehicle,setVehicle]=useState("");const [color,setColor]=useState("");
  async function load(){const r=await fetch("/api/product");const x=await r.json().catch(()=>({}));if(r.status===401){location.href="/login";return;}if(!r.ok){setMessage(x.error||"Unable to load driver tools");return;}setD(x.dashboard);if(!org&&x.dashboard.organizations[0])setOrg(x.dashboard.organizations[0].id);if(x.dashboard.driverProfile){setCapacity(String(x.dashboard.driverProfile.default_capacity||4));setVehicle(x.dashboard.driverProfile.vehicle_label||"");setColor(x.dashboard.driverProfile.vehicle_color||"");}}
  async function configure(enabled=true){setWorking(true);const r=await fetch("/api/onboarding",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"configure_driver",organizationId:org,enabled,capacity:Number(capacity||4),vehicleLabel:vehicle||null,vehicleColor:color||null,willingByDefault:enabled})});const x=await r.json().catch(()=>({}));setWorking(false);if(!r.ok){setMessage(x.error||"Unable to update driver profile");return;}setMessage(enabled?"Driver profile updated.":"Driving paused.");await load();}
  async function offer(requestId:string,seats:number){setWorking(true);const r=await fetch("/api/product",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"offer_ride",rideRequestId:requestId,seatsOffered:Math.max(seats,Number(capacity||4))})});const x=await r.json().catch(()=>({}));setWorking(false);if(!r.ok){setMessage(x.error||"Unable to offer ride");return;}setD(x.dashboard);setMessage("Ride offered. The requester can now accept it.");}
  useEffect(()=>{void load();},[]);
  const input={width:"100%",padding:10,border:"1px solid #cbd5e1",borderRadius:9,margin:"6px 0 12px",boxSizing:"border-box" as const};const button={padding:"10px 14px",border:0,borderRadius:9,background:"#101b33",color:"white",fontWeight:800,cursor:"pointer"} as const;
  const driverUnavailable=!d?.driverProfile||d.driverProfile.status!=="active";
  return <main style={appPageStyle}><AppNav active="Driver"/>{!d?<div style={appCardStyle}>Loading driver tools…</div>:<>
    <section style={{...appCardStyle,marginBottom:18}}><h1 style={{marginTop:0}}>Driver profile</h1><p style={{color:"#64748b"}}>Tell BandWagon how many seats you can offer. You stay in control - matching only suggests rides.</p>{!d.organizations.length?<p>Join an organization before enabling driving.</p>:<><label>Organization</label><select value={org} onChange={e=>setOrg(e.target.value)} style={input}>{d.organizations.map((o:Row)=><option key={o.id} value={o.id}>{o.name}</option>)}</select><label>Available seats</label><input inputMode="numeric" value={capacity} onChange={e=>setCapacity(e.target.value.replace(/\D/g,""))} style={input}/><label>Vehicle label <span style={{color:"#64748b"}}>(optional)</span></label><input value={vehicle} onChange={e=>setVehicle(e.target.value)} placeholder="Blue Tahoe" style={input}/><label>Vehicle color <span style={{color:"#64748b"}}>(optional)</span></label><input value={color} onChange={e=>setColor(e.target.value)} style={input}/><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={working||!org} style={{...button,opacity:working ? .6 : 1}} onClick={()=>configure(true)}>I am willing to drive</button>{d.driverProfile&&<button disabled={working} style={{padding:"10px 14px",border:"1px solid #cbd5e1",borderRadius:9,background:"white",cursor:"pointer"}} onClick={()=>configure(false)}>Pause driving</button>}</div></>}</section>
    <section style={appCardStyle}><h2 style={{marginTop:0}}>Rides needing help</h2>{!d.openRequests.length?<p>No open requests right now.</p>:d.openRequests.map((r:Row)=><div key={r.id} style={{padding:"14px 0",borderBottom:"1px solid #e2e8f0",display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><b>{r.event_title||"Ride request"}</b><div style={{fontSize:13,color:"#64748b",marginTop:3}}>{r.direction.replaceAll("_"," ")} · {r.pickup_area||"Pickup area shared after setup"} · {r.seats_needed} seat(s)</div></div><button disabled={working||driverUnavailable} style={{...button,opacity:driverUnavailable ? .45 : 1}} onClick={()=>offer(r.id,r.seats_needed)}>Offer ride</button></div>)}</section>
  </>}{message&&<div style={{position:"fixed",bottom:20,right:20,maxWidth:380,padding:14,background:"#101b33",color:"white",borderRadius:12}}>{message}</div>}</main>;
}
