"use client";

import { useEffect,useState } from "react";
type Row=Record<string,any>;
export default function SupportModePage(){
  const[q,setQ]=useState(''),[targets,setTargets]=useState<Row[]>([]),[history,setHistory]=useState<Row[]>([]),[reason,setReason]=useState('Troubleshooting reported user issue'),[minutes,setMinutes]=useState('30'),[message,setMessage]=useState(''),[working,setWorking]=useState(false),[bootstrapToken,setBootstrapToken]=useState(''),[needsAccess,setNeedsAccess]=useState(false);
  async function load(search=''){setWorking(true);const r=await fetch(`/api/admin/support-mode${search?`?q=${encodeURIComponent(search)}`:''}`,{cache:'no-store'}),x=await r.json().catch(()=>({}));setWorking(false);if(!r.ok){setNeedsAccess(true);setMessage(x.error||'Platform support access is required.');return;}setNeedsAccess(false);setTargets(x.targets||[]);setHistory(x.history||[]);}
  useEffect(()=>{void load();},[]);
  async function bootstrap(){setWorking(true);const r=await fetch('/api/admin/support-mode/bootstrap',{method:'POST',headers:{'x-bandwagon-admin-token':bootstrapToken}}),x=await r.json().catch(()=>({}));setWorking(false);if(!r.ok){setMessage(x.error||'Unable to bootstrap platform owner');return;}setMessage('Platform owner enabled. Reloading…');location.reload();}
  async function start(target:Row,organizationId:string|null){if(reason.trim().length<5){setMessage('Enter a support reason.');return;}setWorking(true);const r=await fetch('/api/admin/support-mode',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'start',targetUserAccountId:target.user_account_id,targetOrganizationId:organizationId,reason,minutes:Number(minutes),mode:'view'})}),x=await r.json().catch(()=>({}));setWorking(false);if(!r.ok){setMessage(x.error||'Unable to start Support Mode');return;}window.location.href='/app';}
  const card={background:'white',border:'1px solid #e2e8f0',borderRadius:16,padding:18,marginBottom:18} as const,input={width:'100%',padding:11,border:'1px solid #cbd5e1',borderRadius:9,boxSizing:'border-box' as const};
  return <main style={{maxWidth:1100,margin:'32px auto',padding:'0 20px',fontFamily:'system-ui,sans-serif',background:'#f8fafc'}}><header style={{background:'#101b33',color:'white',padding:28,borderRadius:22,marginBottom:18}}><div style={{fontSize:13,fontWeight:900,letterSpacing:1}}>PLATFORM ADMIN</div><h1 style={{fontSize:40,margin:'6px 0'}}>Support Mode</h1><p style={{margin:0,opacity:.9}}>See exactly what a user sees without asking for credentials or taking over their account.</p></header>
  <section style={{...card,background:'#fffbeb',borderColor:'#fcd34d'}}><strong>ViewAs is read-only.</strong> A reason is required, sessions expire automatically, the target and operator are recorded, and BandWagon centrally blocks writes while Support Mode is active.</section>
  {needsAccess&&<section style={card}><h2 style={{marginTop:0}}>First Platform Owner</h2><p style={{color:'#64748b'}}>For initial setup only, sign in to your normal BandWagon account and use the existing Admin Test Token to designate the first platform owner. Once an owner exists, this bootstrap path refuses additional owners.</p><input type="password" value={bootstrapToken} onChange={e=>setBootstrapToken(e.target.value)} placeholder="Admin Test Token" style={input}/><button disabled={working||!bootstrapToken} onClick={bootstrap} style={{marginTop:10,padding:'10px 14px',border:0,borderRadius:9,background:'#101b33',color:'white',fontWeight:800}}>Make My Account Platform Owner</button></section>}
  {!needsAccess&&<><section style={card}><h2 style={{marginTop:0}}>Start ViewAs Session</h2><label><strong>Support Reason</strong></label><input value={reason} onChange={e=>setReason(e.target.value)} style={{...input,margin:'6px 0 12px'}}/><label><strong>Session Length</strong></label><select value={minutes} onChange={e=>setMinutes(e.target.value)} style={{...input,margin:'6px 0 12px'}}><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option></select><label><strong>Find User</strong></label><div style={{display:'flex',gap:8,marginTop:6}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Name or email" style={input}/><button disabled={working||q.trim().length<2} onClick={()=>load(q)} style={{padding:'0 16px',border:0,borderRadius:9,background:'#101b33',color:'white',fontWeight:800}}>Search</button></div>{targets.map(t=><div key={t.user_account_id} style={{padding:'14px 0',borderTop:'1px solid #e2e8f0',marginTop:12}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong>{t.display_name}</strong><div style={{fontSize:13,color:'#64748b'}}>{t.person_type} · {t.organizations?.length||0} organization(s)</div></div><button disabled={working} onClick={()=>start(t,null)} style={{padding:'8px 11px',border:0,borderRadius:8,background:'#101b33',color:'white',fontWeight:800}}>ViewAs All Access</button></div>{Array.isArray(t.organizations)&&t.organizations.length>0&&<div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:9}}>{t.organizations.map((o:Row)=><button key={o.id} disabled={working} onClick={()=>start(t,o.id)} style={{padding:'6px 9px',border:'1px solid #cbd5e1',borderRadius:8,background:'white',cursor:'pointer'}}>View in {o.name}</button>)}</div>}</div>)}</section>
  <section style={card}><h2 style={{marginTop:0}}>Recent Support Sessions</h2>{!history.length?<p>No support sessions yet.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr><th style={{textAlign:'left'}}>Started</th><th style={{textAlign:'left'}}>Operator</th><th style={{textAlign:'left'}}>Target</th><th style={{textAlign:'left'}}>Organization</th><th style={{textAlign:'left'}}>Reason</th><th>Status</th></tr></thead><tbody>{history.map(h=><tr key={h.id} style={{borderTop:'1px solid #e2e8f0'}}><td style={{padding:'10px 0'}}>{new Date(h.started_at).toLocaleString()}</td><td>{h.operator_name}</td><td>{h.target_name}</td><td>{h.organization_name||'All user orgs'}</td><td>{h.reason}</td><td style={{textAlign:'center'}}>{h.status}</td></tr>)}</tbody></table></div>}</section></>}
  {message&&<p style={{padding:14,background:'#eef2ff',borderRadius:10}}>{message}</p>}</main>;
}
