const state = { role:'requester', step:0, offered:false, accepted:false, picked:false, dropped:false, arrival:false };
const stepsByRole = {
 requester:['Dashboard','Create Ride','Privacy Preview','Review Offer','Ride Day','Completed'],
 driver:['Driver Dashboard','Open Match','Offer Ride','Confirmed Ride','Ride Day','Impact'],
 admin:['Organization','Members','Calendars','Ride Health','Privacy & Safety','Statistics']
};
const $ = s=>document.querySelector(s);
const esc = s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function renderSteps(){ const box=$('#steps'); box.innerHTML=''; stepsByRole[state.role].forEach((s,i)=>{const b=document.createElement('button');b.className='step-btn'+(i===state.step?' active':'');b.innerHTML=`<span class="num">${i+1}</span><span>${esc(s)}</span>`;b.onclick=()=>{state.step=i;render()};box.appendChild(b);}); }
function next(){ state.step=Math.min(state.step+1,stepsByRole[state.role].length-1);render(); }
function map(){return `<div class="map"><div class="road"></div><div class="area"></div><div class="pin p1" title="General-area match"></div><div class="pin p2"></div></div><div class="tiny">Demo map only. Production uses Google Maps geocoding and user-drawn service areas. Exact household pins are never shown publicly.</div>`}
function hero(title,desc,badge){return `<div class="hero"><div><h1>${title}</h1><p>${desc}</p></div><span class="badge">${badge}</span></div>`}
function requester(){
 const pages=[
 ()=>`${hero('Welcome back, Harrison','See upcoming events, ride needs, and confirmed transportation for your household.','Requester / Parent')}<div class="stats"><div class="stat"><strong>2</strong><span>Open Requests</span></div><div class="stat"><strong>3</strong><span>Confirmed Rides</span></div><div class="stat"><strong>14</strong><span>Completed This Season</span></div><div class="stat"><strong>0</strong><span>No-Shows</span></div></div><div class="grid" style="margin-top:16px"><div class="card span-7"><h2>Next Ride</h2><div class="row"><div><b>Friday Football Game</b><div class="muted">Katie - Ride Home - 10:15 PM</div></div><span class="pill blue">Confirmed</span></div><div class="divider"></div><div class="profile"><div class="avatar">SS</div><div><b>Sarah Smith</b><div class="muted">Band parent - Wellington area</div><div class="tiny">Phone hidden - use Call / Message relay</div></div></div><div class="actions"><button class="btn primary" onclick="next()">Create Another Ride</button><button class="btn secondary" onclick="state.step=4;render()">View Ride Day</button></div></div><div class="card span-5"><h2>Upcoming Events</h2><div class="event"><b>Friday Football Game</b><div class="muted">Fri 7:00 PM - FMHS</div></div><div class="event"><b>BOA Regional</b><div class="muted">Sat 7:00 AM - Prosper</div></div><div class="event"><b>Guard Practice</b><div class="muted">Tue 4:30 PM - FMHS</div></div></div></div>`,
 ()=>`${hero('Request A Ride','Create one leg or a round trip. Requester and passengers can be different people.','Step 1')}<div class="grid"><div class="card span-7"><div class="form-grid"><div class="field full"><label>Event</label><select><option>Friday Football Game - FMHS</option><option>BOA Regional - Prosper</option><option>Other / Custom</option></select></div><div class="field"><label>Need</label><select><option>Round Trip</option><option>To Event</option><option>From Event</option></select></div><div class="field"><label>Requester</label><select><option>Harrison - Parent</option><option>Katie - Student</option></select></div><div class="field full"><label>Passengers</label><input value="Katie + Emma (2 seats)" /></div><div class="field"><label>Pickup</label><input value="Home - address hidden" /></div><div class="field"><label>Drop-off</label><input value="Flower Mound Band Community Hall" /></div><div class="field full"><label>Transportation Note</label><textarea>2 flag bags + backpacks. Trunk space helpful.</textarea></div><div class="field full"><label>Ride Request Visibility</label><select><option>Color Guard group</option><option>Trusted Connections</option><option>Specific members</option></select></div></div><div class="actions"><button class="btn primary" onclick="next()">Preview Request</button></div></div><div class="card span-5"><h2>General Area</h2>${map()}<div class="callout" style="margin-top:12px">Other members see the selected general area, not the exact home address.</div></div></div>`,
 ()=>`${hero('Privacy Preview','See exactly what is shared before the request is posted.','Privacy First')}<div class="grid"><div class="card span-7"><h2>What The Group Sees</h2><div class="row"><b>Friday Football Game</b><span class="pill warn">Ride Needed</span></div><div class="divider"></div><p><b>Passengers:</b> 2</p><p><b>Need:</b> Round trip</p><p><b>Area:</b> Wellington area</p><p><b>Transportation note:</b> 2 flag bags + backpacks</p><p><b>Exact address:</b> <span class="pill good">HIDDEN</span></p><p><b>Phone:</b> <span class="pill good">HIDDEN</span></p><p><b>Email:</b> <span class="pill good">HIDDEN</span></p><div class="actions"><button class="btn primary" onclick="state.offered=true;next()">Post Demo Request</button></div></div><div class="card span-5"><h2>After You Accept A Driver</h2><p>Only information required to complete the ride is released.</p><ul><li>Passenger first name</li><li>Pickup/drop-off address when necessary</li><li>Ride instructions</li><li>Phone/email only if your visibility settings allow it</li></ul><div class="warnbox"><b>No GPS tracking.</b> Pickup and drop-off are manual confirmations only.</div></div></div>`,
 ()=>`${hero('Sarah Offered To Help','Review a community member before accepting the ride.','Offer Received')}<div class="grid"><div class="card span-7"><div class="profile"><div class="avatar">SS</div><div><h2 style="margin:0">Sarah Smith</h2><div class="muted">Band Parent - Color Guard</div></div></div><p>"Emma is a sophomore in guard. We are around FMHS several nights a week and happy to help when we have room."</p><div class="pill-row"><span class="pill blue">4 max seats</span><span class="pill good">Verified Email</span><span class="pill good">Verified Phone</span></div><div class="divider"></div><p><b>Offer:</b> Can take both passengers TO and FROM the event.</p><p><b>Phone visibility:</b> Hidden - platform Call/Message relay</p><div class="actions"><button class="btn success" onclick="state.accepted=true;next()">Accept Sarah</button><button class="btn secondary">Decline</button><button class="btn secondary">Block</button></div></div><div class="card span-5"><h2>Why This Matched</h2><p>Inside Sarah's selected service area</p><p>Same event</p><p>Enough seats</p><p>Compatible times</p><p>No blocks between households</p><div class="callout">This is a compatibility match, not a safety score or platform endorsement.</div></div></div>`,
 ()=>`${hero('Ride Day','Routine actions can happen in the PWA, RCS, SMS, or email.','1 Hour Reminder')}<div class="grid"><div class="card span-7"><h2>Ride Status</h2><div class="timeline"><div class="timeline-item done"><span class="dot"></span><div><b>Confirmed</b><div class="muted">Sarah + Katie/Emma</div></div></div><div class="timeline-item ${state.picked?'done':'current'}"><span class="dot"></span><div><b>Picked Up</b><div class="muted">Manual confirmation - no location tracking</div></div></div><div class="timeline-item ${state.dropped?'done':state.picked?'current':''}"><span class="dot"></span><div><b>Dropped Off</b></div></div><div class="timeline-item ${state.arrival?'done':state.dropped?'current':''}"><span class="dot"></span><div><b>Arrival Confirmed</b></div></div></div><div class="actions"><button class="btn primary" onclick="state.picked=true;render()">Simulate Picked Up</button><button class="btn success" onclick="state.picked=true;state.dropped=true;render()">Simulate Dropped Off</button><button class="btn secondary" onclick="state.picked=true;state.dropped=true;state.arrival=true;next()">Confirm Arrival</button></div></div><div class="card span-5"><div class="phone"><div class="phone-head">Messages</div><div class="msg"><b>FloMoGo</b><br/>Ride reminder - 1 hour<br/>Sarah is scheduled to pick up Katie and Emma at 6:30 PM.<div class="msg-actions"><button>Still Need Ride</button><button>View Ride</button></div><div class="tiny" style="margin-top:8px">Reply CANCEL if no longer needed.</div></div></div></div></div>`,
 ()=>`${hero('Ride Completed','The ride is complete. No route or location history was collected.','Completed')}<div class="grid"><div class="card span-7"><div class="successbox"><b>Arrival confirmed.</b> Katie and Emma were marked dropped off and the household confirmed arrival.</div><h2 style="margin-top:18px">Your Community Impact</h2><div class="stats"><div class="stat"><strong>15</strong><span>Rides Coordinated</span></div><div class="stat"><strong>15</strong><span>Completed</span></div><div class="stat"><strong>0</strong><span>No-Shows</span></div><div class="stat"><strong>3</strong><span>Trusted Connections</span></div></div><div class="actions"><button class="btn secondary" onclick="state.step=0;render()">Back To Dashboard</button></div></div><div class="card span-5"><h2>Privacy After The Ride</h2><p>Precise ride information is retained only according to the service retention policy.</p><p>You may review privacy settings, download your data, or request deletion.</p><button class="btn secondary" onclick="document.querySelector('#privacyModal').showModal()">Review Privacy</button></div></div>`
 ]; return pages[state.step]();
}
function driver(){
 const pages=[
 ()=>`${hero('Driver Dashboard','See nearby ride needs without exposing passengers\' exact addresses.','Driver')}<div class="stats"><div class="stat"><strong>12</strong><span>Rides Given</span></div><div class="stat"><strong>19</strong><span>Passengers Helped</span></div><div class="stat"><strong>3</strong><span>Upcoming</span></div><div class="stat"><strong>2</strong><span>Open Matches</span></div></div><div class="grid" style="margin-top:16px"><div class="card span-7"><h2>Open In Your Service Area</h2><div class="event"><div class="row"><div><b>Friday Football Game</b><div class="muted">Wellington - 2 passengers - Ride Home</div></div><button class="btn primary" onclick="next()">View</button></div></div><div class="event"><div class="row"><div><b>Guard Practice</b><div class="muted">Bridlewood - 1 passenger - To Event</div></div><button class="btn secondary">View</button></div></div></div><div class="card span-5"><h2>Your Service Area</h2>${map()}<div class="pill-row"><span class="pill good">Matching Active</span><span class="pill blue">4 Max Seats</span></div></div></div>`,
 ()=>`${hero('Open Ride Need','Only enough information is shown to decide whether you may be able to help.','Potential Match')}<div class="grid"><div class="card span-7"><h2>Friday Football Game</h2><p><b>Need:</b> Ride Home</p><p><b>Passengers:</b> 2</p><p><b>General Area:</b> Wellington</p><p><b>Transportation note:</b> 2 flag bags + backpacks</p><p><b>Exact address:</b> <span class="pill good">HIDDEN</span></p><p><b>Phone/email:</b> <span class="pill good">HIDDEN</span></p><div class="actions"><button class="btn success" onclick="next()">I Can Help</button><button class="btn secondary">Not Available</button></div></div><div class="card span-5"><h2>Map Match</h2>${map()}<div class="callout" style="margin-top:12px">The request is inside your Wellington service area. Exact pickup is not disclosed yet.</div></div></div>`,
 ()=>`${hero('Offer A Ride','Tell the requester what you can support.','Offer')}<div class="grid"><div class="card span-7"><div class="form-grid"><div class="field"><label>Direction</label><select><option>From Event</option><option>To Event</option><option>Both</option></select></div><div class="field"><label>Seats Available Tonight</label><select><option>3</option><option>2</option><option>1</option></select></div><div class="field full"><label>Message (optional)</label><textarea>I will already be at the game and can take both kids home.</textarea></div></div><div class="actions"><button class="btn success" onclick="next()">Send Offer</button></div></div><div class="card span-5"><h2>Your Profile Preview</h2><div class="profile"><div class="avatar">SS</div><div><b>Sarah Smith</b><div class="muted">Band Parent - Color Guard</div></div></div><p class="tiny">Your phone number is hidden. If accepted, the requester can contact you through platform relay.</p></div></div>`,
 ()=>`${hero('Ride Confirmed','The requester accepted your offer. Necessary ride details are now available.','Confirmed')}<div class="grid"><div class="card span-7"><h2>Friday Football Game - Ride Home</h2><p><b>Passengers:</b> Katie + Emma</p><p><b>Pickup:</b> Flower Mound Band Community Hall</p><p><b>Drop-off:</b> Exact confirmed stop shown here in production</p><p><b>Transportation note:</b> 2 flag bags + backpacks</p><div class="actions"><button class="btn primary" onclick="next()">Go To Ride Day</button><button class="btn secondary">Call Parent (Relay)</button><button class="btn secondary">Message (Relay)</button></div></div><div class="card span-5"><h2>Privacy Boundary</h2><p>You received the address because you are the confirmed participant on this ride.</p><p>You do not receive the parent or passenger phone/email because their visibility is set to Hidden.</p></div></div>`,
 ()=>`${hero('Ride Day','Use the app or reply to RCS/SMS to update the ride.','Driver Actions')}<div class="grid"><div class="card span-7"><h2>Friday Football Game</h2><div class="actions"><button class="btn primary">I'm On My Way</button><button class="btn primary" onclick="state.picked=true;render()">Picked Up</button><button class="btn success" onclick="state.picked=true;state.dropped=true;next()">Dropped Off</button><button class="btn danger">I Can't Make This Ride</button></div><div class="divider"></div><div class="warnbox"><b>No tracking:</b> these buttons only create timestamped status events. The platform does not collect your route or live location.</div></div><div class="card span-5"><div class="phone"><div class="phone-head">RCS / SMS</div><div class="msg"><b>Ride reminder - 1 hour</b><br/>Katie + Emma - Friday Football Game<div class="msg-actions"><button>Still Good</button><button>Can't Make It</button></div><div class="tiny" style="margin-top:8px">You can also reply YES or CANCEL.</div></div></div></div></div>`,
 ()=>`${hero('Community Impact','Positive recognition without rankings or public ratings.','Impact')}<div class="grid"><div class="card span-7"><div class="stats"><div class="stat"><strong>13</strong><span>Rides Given</span></div><div class="stat"><strong>21</strong><span>Passengers Helped</span></div><div class="stat"><strong>3</strong><span>Upcoming</span></div><div class="stat"><strong>0</strong><span>No-Shows</span></div></div><h2 style="margin-top:18px">Milestones</h2><div class="pill-row"><span class="pill blue">Helping Hand</span><span class="pill blue">10 Rides</span><span class="pill blue">Competition Helper</span></div></div><div class="card span-5"><h2>No Leaderboards</h2><p>Achievements encourage participation but are not used to rank drivers or passengers.</p><div class="callout">The organization sees aggregate ride statistics, not a public "best driver" list.</div></div></div>`
 ]; return pages[state.step]();
}
function admin(){
 const pages=[
 ()=>`${hero('Organization Setup','Configure a tenant without creating an affiliation or agency relationship with the platform.','Organization Admin')}<div class="grid"><div class="card span-7"><h2>Flower Mound Band Community</h2><p><b>Status:</b> <span class="pill good">Active</span></p><p><b>Registration:</b> Code + Admin Approval</p><p><b>Primary Contact:</b> verified</p><p><b>Groups:</b> Marching Band, Color Guard, Percussion, Volunteers</p><div class="actions"><button class="btn primary" onclick="next()">Review Members</button><button class="btn secondary">Create Group Code</button></div></div><div class="card span-5"><h2>Independence Notice</h2><div class="warnbox">Creating an organization space does not mean the platform is owned, operated, sponsored, endorsed, supervised, or managed by that organization or governing body.</div></div></div>`,
 ()=>`${hero('Membership Queue','Organization admins verify community membership, not a person\'s fitness to transport others.','12 Pending')}<div class="card"><div class="event"><div class="row"><div><b>Jennifer Jones</b><div class="muted">Color Guard - Code FMHS26-7K92</div></div><div class="actions"><button class="btn success">Approve</button><button class="btn secondary">Reject</button></div></div></div><div class="event"><div class="row"><div><b>Michael Brown</b><div class="muted">Percussion - Code FMHS26-7K92</div></div><div class="actions"><button class="btn success">Approve</button><button class="btn secondary">Reject</button></div></div></div><div class="actions"><button class="btn primary" onclick="next()">Calendar Connections</button></div></div>`,
 ()=>`${hero('Calendar Connections','Multiple Google and Microsoft calendars can feed the same organization.','Sync Healthy')}<div class="grid"><div class="card span-8"><h2>Connected Sources</h2><div class="event"><div class="row"><div><b>Google Calendar - Band</b><div class="muted">Marching Band - Last sync 6 min ago</div></div><span class="pill good">Healthy</span></div></div><div class="event"><div class="row"><div><b>Google Calendar - Guard</b><div class="muted">Color Guard - Last sync 5 min ago</div></div><span class="pill good">Healthy</span></div></div><div class="event"><div class="row"><div><b>Microsoft 365 - Volunteers</b><div class="muted">Volunteers - Last sync 8 min ago</div></div><span class="pill good">Healthy</span></div></div><div class="actions"><button class="btn primary" onclick="next()">Ride Health</button></div></div><div class="card span-4"><h2>Sync Rules</h2><p>Provider change notifications + periodic reconciliation.</p><p>Material event changes require ride reconfirmation.</p><p>Deleted events are tombstoned, not blindly cascaded.</p></div></div>`,
 ()=>`${hero('Ride Health','Focus on requests that still need help and operational exceptions.','Operations')}<div class="stats"><div class="stat"><strong>48</strong><span>Requested</span></div><div class="stat"><strong>43</strong><span>Matched</span></div><div class="stat"><strong>39</strong><span>Completed</span></div><div class="stat"><strong>2</strong><span>Unmatched</span></div></div><div class="grid" style="margin-top:16px"><div class="card span-8"><h2>Needs Attention</h2><div class="event"><b>BOA Regional - 7:00 AM</b><div class="muted">1 ride still needs driver - escalation eligible</div></div><div class="event"><b>Guard Practice - Tuesday</b><div class="muted">Calendar time changed - 2 rides need reconfirmation</div></div><div class="event"><b>Friday Game</b><div class="muted">1 driver cancellation - request reopened</div></div><div class="actions"><button class="btn primary" onclick="next()">Privacy & Safety</button></div></div><div class="card span-4"><h2>Private Ops</h2><p>Cancellations: 3</p><p>No-show driver: 1</p><p>No-show passenger: 0</p><div class="tiny">No-show data is not a public user score.</div></div></div>`,
 ()=>`${hero('Privacy & Safety','Administrative access does not automatically expose addresses, contact details, or message content.','Trust Center')}<div class="grid"><div class="card span-7"><h2>Controls</h2><p>Personal and household blocking</p><p>Organization membership restriction</p><p>Platform suspension</p><p>Privacy export / deletion queue</p><p>Consent and policy version records</p><p>Security / abuse reporting</p><div class="actions"><button class="btn primary" onclick="next()">View Statistics</button></div></div><div class="card span-5"><h2>Public Documentation</h2><p>How It Works</p><p>What This Service Is NOT</p><p>What People Can See</p><p>Privacy Policy</p><p>Terms of Use</p><p>Data Retention</p><p>Subprocessors</p><p>Security Reporting</p></div></div>`,
 ()=>`${hero('Organization Statistics','Measure whether the community is actually getting rides - without ranking individuals.','Season Dashboard')}<div class="stats"><div class="stat"><strong>326</strong><span>Completed Rides</span></div><div class="stat"><strong>47</strong><span>Volunteer Drivers</span></div><div class="stat"><strong>88</strong><span>Passengers Helped</span></div><div class="stat"><strong>91%</strong><span>Match Rate</span></div></div><div class="grid" style="margin-top:16px"><div class="card span-7"><h2>Demand vs Completion</h2><div class="event"><div class="row"><b>Requested</b><b>358</b></div></div><div class="event"><div class="row"><b>Matched</b><b>337</b></div></div><div class="event"><div class="row"><b>Completed</b><b>326</b></div></div><div class="event"><div class="row"><b>Unmatched</b><b>21</b></div></div></div><div class="card span-5"><h2>Community Impact</h2><p>Celebrate aggregate participation rather than publishing individual leaderboards.</p><div class="callout">"326 rides completed this season by 47 volunteer drivers."</div></div></div>`
 ]; return pages[state.step]();
}
function render(){ renderSteps(); $('#screen').innerHTML=state.role==='requester'?requester():state.role==='driver'?driver():admin(); }
document.querySelectorAll('.persona').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.persona').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.role=b.dataset.role;state.step=0;render()}));
$('#privacyBtn').onclick=()=>$('#privacyModal').showModal(); $('#closePrivacy').onclick=()=>$('#privacyModal').close();
$('#resetBtn').onclick=()=>{Object.assign(state,{step:0,offered:false,accepted:false,picked:false,dropped:false,arrival:false});render()};
render();


// Demo-only PWA install instructions
const installHelpBtn = document.getElementById('installHelpBtn');
const installModal = document.getElementById('installModal');
const closeInstall = document.getElementById('closeInstall');
if (installHelpBtn && installModal) installHelpBtn.addEventListener('click', () => installModal.showModal());
if (closeInstall && installModal) closeInstall.addEventListener('click', () => installModal.close());
