"use client";

import { useEffect,useState } from "react";

type Row=Record<string,any>;
function percentBar(value:number){return <div style={{height:9,background:'#e2e8f0',borderRadius:999,overflow:'hidden',minWidth:120}}><div style={{height:'100%',width:`${Math.max(0,Math.min(100,value))}%`,background:'#101b33'}}/></div>}
export default function PlatformAdminPage(){
  const[data,setData]=useState<Row|null>(null),[message,setMessage]=useState(''),[token,setToken]=useState(''),[working,setWorking]=useState(false);
  async function load(adminToken=token){setWorking(true);setMessage('');const headers:Record<string,string>={};if(adminToken)headers['x-bandwagon-admin-token']=adminToken;const r=await fetch('/api/admin/platform',{headers,cache:'no-store'}),x=await r.json().catch(()=>({}));setWorking(false);if(!r.ok){setMessage(x.error||'Platform administrator access is required.');return;}setData(x.overview);}
  useEffect(()=>{void load('');},[]);
  const card={background:'white',border:'1px solid #e2e8f0',borderRadius:16,padding:18} as const;
  const metric=(label:string,value:any,detail?:string)=><div style={card}><div style={{fontSize:12,fontWeight:900,letterSpacing:.7,color:'#64748b'}}>{label.toUpperCase()}</div><div style={{fontSize:32,fontWeight:950,marginTop:5}}>{value}</div>{detail&&<div style={{fontSize:13,color:'#64748b',marginTop:4}}>{detail}</div>}</div>;
  return <main style={{maxWidth:1200,margin:'32px auto',padding:'0 20px',fontFamily:'system-ui,sans-serif',background:'#f8fafc'}}>
    <header style={{background:'#101b33',color:'white',padding:28,borderRadius:22,marginBottom:18}}><div style={{fontSize:13,fontWeight:900,letterSpacing:1}}>PLATFORM ADMIN</div><h1 style={{fontSize:40,margin:'6px 0'}}>BandWagon Overview</h1><p style={{margin:0,opacity:.88}}>Usage, adoption, health and the answer to “are people actually using what we built?”</p><div style={{display:'flex',gap:10,marginTop:18,flexWrap:'wrap'}}><a href="/admin/support-mode" style={{color:'#101b33',background:'white',padding:'8px 12px',borderRadius:9,fontWeight:800,textDecoration:'none'}}>Support Mode</a><a href="/admin/budget" style={{color:'white',border:'1px solid #64748b',padding:'8px 12px',borderRadius:9,fontWeight:800,textDecoration:'none'}}>Cost Guardrails</a><a href="/admin/operations" style={{color:'white',border:'1px solid #64748b',padding:'8px 12px',borderRadius:9,fontWeight:800,textDecoration:'none'}}>Org Operations</a></div></header>
    {!data&&<section style={card}><h2 style={{marginTop:0}}>Platform Access</h2><p style={{color:'#64748b'}}>Sign in with a platform-admin account. During initial bootstrap, the existing Admin Test Token can also load this page.</p><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Admin Test Token" style={{width:'100%',maxWidth:460,padding:11,border:'1px solid #cbd5e1',borderRadius:9,boxSizing:'border-box'}}/><button disabled={working} onClick={()=>load()} style={{marginLeft:8,padding:'10px 14px',border:0,borderRadius:9,background:'#101b33',color:'white',fontWeight:800}}>Load</button></section>}
    {data&&<><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,marginBottom:18}}>{metric('Active Organizations',data.headline.activeOrganizations,`${data.headline.totalOrganizations} total`)}{metric('Monthly Active Users',data.headline.monthlyActiveUsers,`${data.headline.weeklyActiveUsers} active in 7d`)}{metric('New Users',data.headline.newUsers30,'last 30 days')}{metric('Active Drivers',data.headline.activeDrivers)}{metric('Rides',data.headline.rides30,`${data.headline.completedRides30} completed in 30d`)}{metric('SMS / RCS Share',`${data.messaging.smsSharePercent}%`,`${data.messaging.smsRcs30} of ${data.messaging.total30} notifications`)}</section>
    <section style={{...card,marginBottom:18}}><h2 style={{marginTop:0}}>Feature Adoption</h2><p style={{color:'#64748b'}}>The denominator changes by feature so the percentage stays meaningful. RouteAssist compares enabled drivers to active drivers; AI compares opted-in organizations to active organizations; Verified Pickup measures completed handshakes against attempts.</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr><th style={{textAlign:'left',padding:'10px 8px'}}>Feature</th><th style={{textAlign:'left'}}>Adoption</th><th style={{textAlign:'right'}}>Count</th><th style={{textAlign:'right'}}>Usage</th><th style={{textAlign:'left',paddingLeft:18}}>Detail</th></tr></thead><tbody>{data.features.map((f:Row)=><tr key={f.key} style={{borderTop:'1px solid #e2e8f0'}}><td style={{padding:'13px 8px',fontWeight:900}}>{f.label}</td><td><div style={{display:'flex',alignItems:'center',gap:9}}>{percentBar(f.percent)}<strong>{f.percent}%</strong></div></td><td style={{textAlign:'right'}}>{f.numerator}/{f.denominator}</td><td style={{textAlign:'right',fontWeight:800}}>{f.usage30}</td><td style={{paddingLeft:18,color:'#64748b',fontSize:13}}>{f.detail}</td></tr>)}</tbody></table></div></section>
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:14}}><div style={card}><h2 style={{marginTop:0}}>Messaging Health</h2><p><strong>{data.messaging.total30}</strong> notifications in 30 days</p><p><strong>{data.messaging.smsRcs30}</strong> SMS / RCS fallbacks</p><p><strong>{data.messaging.failed30}</strong> failed / undelivered</p></div><div style={card}><h2 style={{marginTop:0}}>24-Hour Health</h2><p><strong>{data.health.aiFailures24}</strong> AI failures</p><p><strong>{data.health.notificationFailures24}</strong> notification failures</p><p style={{fontSize:13,color:'#64748b'}}>Next: integration/cron/storage/database health will roll into this panel.</p></div></section></>}
    {message&&<p style={{padding:14,background:'#fff7ed',border:'1px solid #fed7aa',borderRadius:10}}>{message}</p>}
  </main>;
}
