"use client";

import { useEffect,useState } from "react";
import { AppNav,appCardStyle,appPageStyle } from "@/components/app-nav";

type Row=Record<string,any>;

export default function NotificationSettingsPage(){
  const [orgs,setOrgs]=useState<Row[]>([]);const [org,setOrg]=useState("");const [prefs,setPrefs]=useState<Row|null>(null);const [summary,setSummary]=useState<Row[]>([]);const [recent,setRecent]=useState<Row[]>([]);const [message,setMessage]=useState("");const [working,setWorking]=useState(false);
  useEffect(()=>{void bootstrap();},[]);
  async function bootstrap(){const r=await fetch("/api/product");const x=await r.json().catch(()=>({}));if(r.status===401){location.href="/login";return;}const rows=x.dashboard?.organizations||[];setOrgs(rows);const id=rows[0]?.id||"";setOrg(id);await load(id);}
  async function load(id=org){const r=await fetch(`/api/notification-preferences${id?`?organizationId=${encodeURIComponent(id)}`:""}`);const x=await r.json().catch(()=>({}));if(!r.ok){setMessage(x.error||"Unable to load preferences");return;}setPrefs(x.preferences);setSummary(x.deliverySummary||[]);setRecent(x.recentDeliveries||[]);}
  async function save(next:Row){setWorking(true);const r=await fetch("/api/notification-preferences",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId:org||null,...next})});const x=await r.json().catch(()=>({}));setWorking(false);if(!r.ok){setMessage(x.error||"Unable to save preferences");return;}setPrefs(x.preferences);setSummary(x.deliverySummary||[]);setRecent(x.recentDeliveries||[]);setMessage("Notification preferences saved.");}
  function toggle(key:string,label:string,help:string,locked=false){const checked=Boolean(prefs?.[key]);return <label style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"center",padding:"14px 0",borderBottom:"1px solid #e2e8f0"}}><div><strong>{label}</strong><div style={{fontSize:13,color:"#64748b",marginTop:3}}>{help}</div></div><input type="checkbox" checked={checked} disabled={working||locked} onChange={e=>save({[key.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]:e.target.checked})} style={{width:22,height:22}}/></label>}
  const totalCost=summary.reduce((n,r)=>n+Number(r.estimated_cost_cents||0),0);
  return <main style={appPageStyle}><AppNav active="Settings"/><nav aria-label="Settings sections" style={{display:"flex",gap:8,marginBottom:18}}><a href="/app/settings/notifications" aria-current="page" style={{padding:"9px 12px",borderRadius:9,background:"#101b33",color:"white",textDecoration:"none",fontWeight:800}}>Notifications</a><a href="/app/settings/privacy" style={{padding:"9px 12px",borderRadius:9,background:"#f1f5f9",color:"#334155",textDecoration:"none",fontWeight:800}}>Privacy &amp; Data</a></nav><section style={{...appCardStyle,marginBottom:18}}><div style={{fontSize:13,fontWeight:950,letterSpacing:1,color:"#64748b"}}>NOTIFICATIONS</div><h1 style={{margin:"7px 0"}}>Stay informed without getting spammed.</h1><p style={{color:"#475569"}}>Routine notifications prefer Push. SMS/RCS is reserved for important fallbacks and critical ride/safety events by default.</p>{orgs.length>0&&<label style={{fontWeight:800}}>Organization<select value={org} onChange={e=>{setOrg(e.target.value);void load(e.target.value);}} style={{display:"block",width:"100%",marginTop:6,padding:10,border:"1px solid #cbd5e1",borderRadius:9}}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}</section>
    {prefs&&<section style={{...appCardStyle,marginBottom:18}}><h2 style={{marginTop:0}}>Channels</h2>{toggle("push_enabled","Push notifications","Best for routine ride updates and reminders.")}{toggle("email_enabled","Email fallback","Used when appropriate if Push is unavailable.")}{toggle("sms_enabled","SMS / RCS","Keep enabled for critical ride and safety communication.")}{toggle("sms_for_critical_only","SMS only for critical events","Recommended to minimize cost and notification noise.")}<h2>Ride Reminders</h2>{toggle("reminder_push_enabled","Push reminders","24-hour and 1-hour ride reminders.")}{toggle("reminder_email_enabled","Email reminders","Optional reminder copies by email.")}{toggle("reminder_sms_enabled","SMS reminders","Optional; may increase messaging cost.")}<div style={{marginTop:16,padding:12,background:"#fff7ed",borderRadius:10,fontSize:13}}>Emergency Assist and platform-required safety communications may still use the safest available critical channel even when routine preferences are restrictive.</div></section>}
    <section style={{...appCardStyle,marginBottom:18}}><h2 style={{marginTop:0}}>Delivery Health - Last 30 Days</h2><div style={{fontSize:30,fontWeight:950}}>${totalCost.toFixed(2)}</div><div style={{fontSize:13,color:"#64748b",marginBottom:14}}>Estimated messaging cost associated with your recorded deliveries.</div>{!summary.length?<p>No delivery activity yet.</p>:summary.map((r,i)=><div key={`${r.channel}-${r.status}-${i}`} style={{display:"flex",justifyContent:"space-between",padding:"8px 0",borderBottom:"1px solid #e2e8f0"}}><span>{String(r.channel).toUpperCase()} · {r.status}</span><strong>{r.count}</strong></div>)}</section>
    <section style={appCardStyle}><h2 style={{marginTop:0}}>Recent Deliveries</h2>{!recent.length?<p>No recent deliveries.</p>:recent.map((r,i)=><div key={i} style={{padding:"9px 0",borderBottom:"1px solid #e2e8f0"}}><strong>{r.notification_type.replaceAll("_"," ")}</strong><div style={{fontSize:13,color:"#64748b"}}>{String(r.channel).toUpperCase()} · {r.status} · {new Date(r.created_at).toLocaleString()}</div></div>)}</section>
    {message&&<div style={{position:"fixed",right:20,bottom:20,maxWidth:500,padding:14,borderRadius:12,background:"#101b33",color:"white"}}>{message}</div>}
  </main>;
}
